In [19]:
import pandas as pd
import numpy as np

In [20]:
df = pd.read_csv('movies_dataset.csv')
df.head(3)

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/e4OnHU8HNAhdS6C4Ypk6NA26kPQ.jpg,"[28, 35, 80]",1168190,en,The Wrecking Crew,Estranged half-brothers Jonny and James reunit...,673.3304,/gbVwHl4YPSq6BcC92TQpe7qUTh6.jpg,2026-01-28,The Wrecking Crew,False,6.741,346
1,False,/tyjXlexbNZQ0ZT1KEJslQtBirqc.jpg,"[12, 53, 878]",840464,en,Greenland 2: Migration,Having found the safety of the Greenland bunke...,624.2323,/1mF4othta76CEXcL1YFInYudQ7K.jpg,2026-01-07,Greenland 2: Migration,False,6.472,301
2,False,/5h2EsPKNDdB3MAtOk9MB9Ycg9Rz.jpg,"[16, 35, 12, 10751, 9648]",1084242,en,Zootopia 2,After cracking the biggest case in Zootopia's ...,340.0179,/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg,2025-11-26,Zootopia 2,False,7.630,1506

In [21]:
df.columns

Index(['adult', 'backdrop_path', 'genre_ids', 'id', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'release_date', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='object')

In [22]:
df.columns = ['adulto', 'caminho_do_pano_de_fundo', 'id_dos_gêneros', 'id', 'idioma_original',
'título_original', 'visão_geral', 'popularidade', 'caminho_do_pôster',
'data_de_lançamento', 'título', 'vídeo', 'média_de_votos', 'contagem_de_votos']
df.head(3)

,adulto,caminho_do_pano_de_fundo,id_dos_gêneros,id,idioma_original,título_original,visão_geral,popularidade,caminho_do_pôster,data_de_lançamento,título,vídeo,média_de_votos,contagem_de_votos
0,False,/e4OnHU8HNAhdS6C4Ypk6NA26kPQ.jpg,"[28, 35, 80]",1168190,en,The Wrecking Crew,Estranged half-brothers Jonny and James reunit...,673.3304,/gbVwHl4YPSq6BcC92TQpe7qUTh6.jpg,2026-01-28,The Wrecking Crew,False,6.741,346
1,False,/tyjXlexbNZQ0ZT1KEJslQtBirqc.jpg,"[12, 53, 878]",840464,en,Greenland 2: Migration,Having found the safety of the Greenland bunke...,624.2323,/1mF4othta76CEXcL1YFInYudQ7K.jpg,2026-01-07,Greenland 2: Migration,False,6.472,301
2,False,/5h2EsPKNDdB3MAtOk9MB9Ycg9Rz.jpg,"[16, 35, 12, 10751, 9648]",1084242,en,Zootopia 2,After cracking the biggest case in Zootopia's ...,340.0179,/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg,2025-11-26,Zootopia 2,False,7.630,1506

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   adulto                    10000 non-null  bool
 1   caminho_do_pano_de_fundo  7023 non-null   object
 2   id_dos_gêneros            10000 non-null  object
 3   id                        10000 non-null  int64
 4   idioma_original           10000 non-null  object
 5   título_original           10000 non-null  object
 6   visão_geral               9650 non-null   object
 7   popularidade              10000 non-null  float64
 8   caminho_do_pôster         9242 non-null   object
 9   data_de_lançamento        9852 non-null   object
 10  título                    10000 non-null  object
 11  vídeo                     10000 non-null  bool
 12  média_de_votos            10000 non-null  float64
 13  contagem_de_votos         10000 non-null  int64
dtypes: bool(2), float64(2), int64(2), object(8)
memory usage: 957.2+ KB

In [24]:
df['idioma_original'].unique()

array(['en', 'zh', 'hi', 'de', 'te', 'ko', 'ja', 'th', 'fr', 'ta', 'tl',
       'pt', 'fi', 'es', 'ml', 'id', 'tr', 'it', 'kn', 'no', 'ru', 'ms',
       'sr', 'ca', 'nl', 'da', 'cn', 'sv', 'lv', 'el', 'cs', 'hu', 'pl',
       'is', 'sl', 'ro', 'hr', 'bs', 'uk', 'ar', 'bn', 'sh', 'sk', 'eu',
       'et', 'fa', 'xx', 'pa', 'sq', 'af', 'ne', 'ku', 'yi', 'mr', 'zu',
       'bg', 'ur', 'he', 'ab', 'mk', 'lt', 'jv', 'az', 'hy', 'cy', 'vi',
       'mn', 'ga', 'gu', 'as', 'qu', 'xh', 'wo'], dtype=object)

In [25]:
df['média_de_votos'].value_counts().head(10)

média_de_votos
0.0    2165
6.0     361
5.0     341
7.0     230
5.5     169
6.5     148
4.0     126
6.2     122
5.7     117
5.8     116
Name: count, dtype: int64

In [26]:
valores_baixo = df['média_de_votos'] == 0
df[valores_baixo].head(3)

,adulto,caminho_do_pano_de_fundo,id_dos_gêneros,id,idioma_original,título_original,visão_geral,popularidade,caminho_do_pôster,data_de_lançamento,título,vídeo,média_de_votos,contagem_de_votos
82,False,NaN,"[99, 36, 10752]",1409999,en,World War II: A History of WWII (Part 2),This documentary begins with the story of the ...,33.4954,/f7fbDkpe5PcEBdgBs1qnwCcOWD7.jpg,2001-01-01,World War II: A History of WWII (Part 2),False,0.0,0
101,False,/wDKJqWo8bwqdJCPQJNemeRDioKI.jpg,[],1483088,tr,Aşkın Yüzü,High school student Özgür has a rare disease: ...,25.2208,/1yhTZRtl7ZSMoPGpmMhL1iq0fxD.jpg,2025-06-06,Aşkın Yüzü,False,0.0,0
119,False,/4lo5yNZrMLPKBh47t2CoZkbAUur.jpg,"[16, 35, 10751, 28]",1297842,en,GOAT,"Will, a small goat with big dreams, gets a onc...",24.7503,/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg,2026-02-11,GOAT,False,0.0,0

In [27]:
df['contagem_de_votos'].value_counts()

contagem_de_votos
0        2162
1         749
2         556
3         401
4         293
         ...
6276        1
6846        1
1254        1
377         1
10363       1
Name: count, Length: 1442, dtype: int64

In [30]:
df['idioma_original'].value_counts(normalize=True) * 100

idioma_original
en    57.67
fr     5.06
de     3.99
es     3.93
ja     3.38
      ...
az     0.01
jv     0.01
ab     0.01
ku     0.01
wo     0.01
Name: proportion, Length: 73, dtype: float64

In [ ]:
df