In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('US_Baby_Names_1880_2024 (1).csv')
df.columns

Index(['year', 'name', 'sex', 'count'], dtype='object')

In [3]:
df.head(3)

   year  name sex  count
0  1880  Mary   F   7065
1  1880  Anna   F   2604
2  1880  Emma   F   2003

In [4]:
df.shape

(2149477, 4)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149477 entries, 0 to 2149476
Data columns (total 4 columns):
 #   Column  Dtype
---  ------  -----
 0   year    int64
 1   name    object
 2   sex     object
 3   count   int64
dtypes: int64(2), object(2)
memory usage: 65.6+ MB

In [6]:
df[df['year'] > 2020]

         year       name sex  count
2021942  2021     Olivia   F  17841
2021943  2021       Emma   F  15543
2021944  2021  Charlotte   F  13362
2021945  2021     Amelia   F  13032
2021946  2021        Ava   F  12867
...       ...        ...  ..    ...
2149472  2024      Zylyn   M      5
2149473  2024    Zymiere   M      5
2149474  2024     Zypher   M      5
2149475  2024       Zyre   M      5
2149476  2024     Zyrell   M      5

[127535 rows x 4 columns]

In [7]:
df['name'].value_counts()

name
Johnnie      290
Sidney       290
Marion       290
Jesse        290
Jessie       290
            ...
Brodney        1
Anjeliett      1
Analyz         1
Codera         1
Zyloh          1
Name: count, Length: 104819, dtype: int64

In [8]:
df['sex'].value_counts()

sex
F    1263426
M     886051
Name: count, dtype: int64

In [9]:
df.isnull().sum()

year     0
name     0
sex      0
count    0
dtype: int64

In [13]:
df[df['name'].str.startswith('J')]

         year       name sex  count
23       1880     Jennie   F    793
25       1880      Julia   F    783
35       1880     Jessie   F    635
49       1880  Josephine   F    544
97       1880       Jane   F    215
...       ...        ...  ..    ...
2148394  2024     Justan   M      5
2148395  2024     Juvens   M      5
2148396  2024      Jyere   M      5
2148397  2024     Jymere   M      5
2148398  2024      Jyzir   M      5

[161346 rows x 4 columns]

In [17]:
coluna_masc = df[df['sex'] == 'M']
coluna_masc.sort_values(by='name')

         year    name sex  count
1586661  2007   Aaban   M      5
1654983  2009   Aaban   M      6
1686502  2010   Aaban   M      9
1953793  2018   Aaban   M      7
1818412  2014   Aaban   M     16
...       ...     ...  ..    ...
1658526  2009  Zyvion   M      5
1856777  2015   Zyvon   M      7
1825035  2014   Zyyon   M      6
1692631  2010   Zzyzx   M      5
1958234  2018   Zzyzx   M      5

[886051 rows x 4 columns]

In [18]:
coluna_masc.query('year < 2000')

         year     name sex  count
942      1880     John   M   9655
943      1880  William   M   9532
944      1880    James   M   5927
945      1880  Charles   M   5348
946      1880   George   M   5126
...       ...      ...  ..    ...
1333144  1999    Zyier   M      5
1333145  1999   Zyquan   M      5
1333146  1999   Zyquez   M      5
1333147  1999    Zyron   M      5
1333148  1999  Zyshaun   M      5

[539493 rows x 4 columns]

In [19]:
df['sex'].value_counts()

sex
F    1263426
M     886051
Name: count, dtype: int64

In [21]:
df.query('sex == "F" & year < 2000')

         year       name sex  count
0        1880       Mary   F   7065
1        1880       Anna   F   2604
2        1880       Emma   F   2003
3        1880  Elizabeth   F   1939
4        1880     Minnie   F   1746
...       ...        ...  ..    ...
1321531  1999      Zohal   F      5
1321532  1999     Zophia   F      5
1321533  1999       Zuha   F      5
1321534  1999      Zuhal   F      5
1321535  1999       Zuzu   F      5

[793656 rows x 4 columns]