In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('US_Baby_Names_1880_2024 (1).csv')
df.columns

Index(['year', 'name', 'sex', 'count'], dtype='object')

In [3]:
df.head(3)

   year  name sex  count
0  1880  Mary   F   7065
1  1880  Anna   F   2604
2  1880  Emma   F   2003

In [5]:
df.shape

(2149477, 4)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149477 entries, 0 to 2149476
Data columns (total 4 columns):
 #   Column  Dtype
---  ------  -----
 0   year    int64
 1   name    object
 2   sex     object
 3   count   int64
dtypes: int64(2), object(2)
memory usage: 65.6+ MB

In [11]:
df[df['year'] > 2020]

         year       name sex  count
2021942  2021     Olivia   F  17841
2021943  2021       Emma   F  15543
2021944  2021  Charlotte   F  13362
2021945  2021     Amelia   F  13032
2021946  2021        Ava   F  12867
...       ...        ...  ..    ...
2149472  2024      Zylyn   M      5
2149473  2024    Zymiere   M      5
2149474  2024     Zypher   M      5
2149475  2024       Zyre   M      5
2149476  2024     Zyrell   M      5

[127535 rows x 4 columns]